### PR TITLE
[website] Migrate to Docusaurus v2

### PR DESCRIPTION
**Pull request by RDIL**
Hi!

Docusaurus v1 is no longer suggested by the Docusaurus team, and even though v2 is still in alpha, its really just a title as it is quite stable.  

I set up a preview site here: https://vigilant-curran-2cef5b.netlify.app/immer/

Signed-off-by: Reece Dunham <me@rdil.rocks>

### CODE REVIEW

**Comment by mweststrate** [comment]
Hi @RDIL, thanks for taking this effort. Are there any specific benefits of using docusaurus v2 at the moment?

**Comment by RDIL** [comment]
> 
> 
> Hi @RDIL, thanks for taking this effort. Are there any specific benefits of using docusaurus v2 at the moment?

Hey, sorry for not getting back sooner!

The benefits include improved design, a dark mode, JavaScript page transitions (so the page never reloads, making it faster as well), improved SEO, and more.

**Comment by mweststrate** [comment]
Merged with some tweaks, thanks!

**Comment by RDIL** [comment]
It looks like this needs to be manually deployed?

**Comment by mweststrate** [comment]
Yeah just did so

**Pull request merged**
