### PR TITLE
feat: Always use remove command in generateArrayPatches()

### LINKED ISSUE #208: Patch for array.pop() replaces "length"
Let's assume `array = [ 0 ]`. Should `array.pop()` result in `{ op: "remove", path: [ "0" ] }` instead of `{ op: "replace", path: [ "length" ], value: 0 }`?

I guess Immer is already "breaking" from [the spec](https://tools.ietf.org/html/rfc6902) by making `path` an array and not `/foo/bar`, but you could argue replacing `length` isn't friendly to non-JS environments.

I assume the current behavior improves performance slightly.

https://codesandbox.io/s/0o1zx5226l

  * Version: **1.7.2**
  * [X] Occurs when using Proxies (use `setUseProxies(true)`)
  * [X] Occurs in the ES5 implementation (use `setUseProxies(false)`)

### PR DESCRIPTION
**Pull request by jsdevtom**
Fixes #208
Please look for things I haven't tested. I found the part of the code that I was reading very hard to understand due to the lack of descriptive names and unexpected swapping of those variable names that I did understand (see https://github.com/immerjs/immer/blob/master/src/patches.js#L15). For this reason I am not sure that I have not introduced unexpected behavior.

### CODE REVIEW

**Comment by mweststrate** [comment]
Looks great at first sight! Will study it in more detail when cutting next release

**Comment by mfix22** [comment]
Such a cool PR! Fixing bugs by _deleting_ code. Looks like the right move 🎉

**Comment by mweststrate** [comment]
Looks correct to me!

**Pull request merged**
