### PR TITLE
Proxy: Ignore setting a reference to itself

### PR DESCRIPTION
**Pull request by smirea**

### CODE REVIEW

**Comment by mweststrate** [comment]
Please make sure that tests proof what was suboptimal before, and works better now

**Comment by mweststrate** [comment]
@smirea do you intend to work on this PR further in the future?

**Comment by smirea** [comment]
oh hey, missed your previous comment, sure I can add tests to it and submit it properly, I just wasn't sure if that was the right approach

**Comment by mweststrate** [comment]
Me neither until I see which problem it fixes ;-)

**Comment by smirea** [comment]
ok updated the PR with a test outlining the issue if you can take another look

**Comment by smirea** [comment]
@mweststrate I added the test, mind giving it another look? This is related to #648

**Pull request merged**
