### PR TITLE
Make  `applyPatches` to accept  `readonly Patch[]`

### PR DESCRIPTION
**Pull request by Andarist**
My main goal is for `applyPatches` to accept `readonly Patch[]` as there is no reason why it shouldn't accept it. If you think that other changes here are too risky (like returning `readonly Patch[]` from `produceWithPatches`) then I can revert those bits of this change.

### CODE REVIEW

**Comment by mweststrate** [comment]
Yeah that looks great! I'm not 100% sure about the returned patches indeed, as people might be postprocessing those in a mutable manner. So probably safer to not change right away. (Feel free to set up a separate PR to park for the next major)

**Comment by mweststrate** [comment]
Looks like some of the tests fail, but overall agree with the idea :)

**Comment by Andarist** [comment]
@mweststrate I adjusted the PR as requested. There are still some test failures here but they are unrelated to the change - the same ones can be seen `main`

**Comment by mweststrate** [comment]
I didn't use GitHub for too long and can't find the rebase button anymore, but master should be fixed now.

**Comment by Andarist** [comment]
Just rebased this on top of `main` - it should be ready to go

**Comment by mweststrate** [comment]
Merging, thanks for the PR and sorry for the delay!

**Pull request merged**
