### PR TITLE
[minor] Add failing test for nested and chained produce calls

### PR DESCRIPTION
**Pull request by jpallen**

### CODE REVIEW

**Comment by mweststrate** [comment]
Putting on hold for now, as the test looks legit but contrived, so some context on the original problem this is addressing would be needed to be able to figure this one out.

**Comment by mweststrate** [comment]
Ah, this might relate to #917, will check on top of that

**Comment by jpallen** [comment]
Thanks for looking at this. This test is capturing the bug I described in https://github.com/immerjs/immer/issues/936, which has a bit more context as to what conditions triggered this error.

**Comment by mweststrate** [comment]
NOTE: will merge this diff, which will break main, but otherwise I have to cherrypick the test and the original attribution to @jpallen  would be lost :)

**Pull request merged**
